
[font]
size = 15.0

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 25
y = 25

[window]
opacity = 1.0

[terminal]
